### ISSUE TITLE
Add background color to header in mobile on scroll 

### ISSUE THREAD

**Issue by rishabhrathod01** [narendrasss/NotANumber#15]
## Description
Currently when user scrolls the webpage in mobile, header's text and content of the web page overlaps.

### Screenshot
![NAN_Resp_issue](https://user-images.githubusercontent.com/23132741/117455140-82bdcf80-af64-11eb-9c2b-be6f9aa43296.jpeg)

Let me know if PR are welcomed :)

**Comment by narendrasss** [comment]
Hi there, thanks for the issue! Not accepting PRs at the moment, but I appreciate opening the issue :)
