### ISSUE TITLE
Scrollbar UI enhancement 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [narendrasss/NotANumber#16]
## Description
In the content of the blog, scrollbar UI can be improved by reducing width and changing color.

### Screenshot (current UI)
![image](https://user-images.githubusercontent.com/23132741/117459337-e9dd8300-af68-11eb-9364-a07ab9a41942.png)

Let me know if PR are welcomed, i would like to resolve it :)

**Comment by narendrasss** [comment]
Thanks for the issue! Some other people have pointed out this problem to me as well. Not accepting PRs at the moment, but will take a look.

**Comment by narendrasss** [comment]
This is fixed on the latest!
