### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by TroyKomodo** [narendrasss/NotANumber#57]
I really like your project. Seeing how nice your portfolio is I have decided to make one too.

One thing tho.

Use lazy loading. Currently your JS bundle is massive. lazy loading will allow for better code splitting and also would allow your portfolio to render faster. (I noticed while navigating to your page for the first time, the vercel cache missed and the styles were broken for the first 5s of page load)

Currently on page load your portfolio loads all the JavaScript & styles to display every page when we don't need that stuff at first page load. 

Another thing is enable QUIC (not sure if vercel has this cloudflare does) QUIC reduces the first handshakes from the server and allows for the slight latency delay to be removed due to the QUIC stream protocol and how it requires only a 3 way handshake to get going vs a 7.

other than those the actual portfolio is really impressive.
Super nicely polished!

**Comment by TroyKomodo** [comment]
![image](https://user-images.githubusercontent.com/49777269/195133919-8c33942a-fe31-4288-82c6-38c99863e583.png)
Notice how all the JS loads and then waits for the others to complete.

I just noticed no raw styles? Likely why it took 5s for page to load because it had to download all the JS and then execute it + cache miss which added on to it. 

Another thing since this site is basically static, you could deploy it prerendered. There is no logic for state anywhere so there isnt really a need for a server or api serving or rendering the content.

**Comment by narendrasss** [comment]
Hey, really appreciate the detailed feedback! I'm currently working on a pretty massive rewrite (https://github.com/narendrasss/NotANumber/pull/55) that should hopefully fix a bunch of these performance problems.

The current version of the site is unfortunately built on a rather old version of Next and uses a pretty poor MDX integration. The new version should be up soon!
