### ISSUE TITLE
Can't browse the site with keyboard

### ISSUE THREAD

**Issue by SleeplessByte** [narendrasss/NotANumber#64]
Hi there! 

I really like the content, but I'm having a lot of difficulty reading and exploring it, because of two problems:

1. focus styles are missing
2. some links lack `href` and seem to be using some `onclick` handler

For example on the index page the following three links I cannot see when tabbed to, or are no tab-enabled at all:

1. Subscribe to the newsletter (invisible focus)
2. Inside Framer's Magic Motion (no href, thus no tab-stop)
3. Rebuilding Babel: The Tokenizer (no href, thus no tab-stop)

Another example is on the blog posts themselves, the buttons, such as Toggle, don't have focus styles. 

I would love it if I could browse the content without needing a mouse ❤️

**Comment by narendrasss** [comment]
Thanks for the feedback! The `href` problems should be fixed now. I'll work on the improved focus styles shortly!
